### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by SergSukh** [ss3nclam/ex_test#1]
Добрый день, Глеб.
В целом хорошая работа, но есть куда расти.

Задача:
1. Обязательно: При первоначальной настройке и запуске компоуза коллектор начнет работать и собирать данные.
- Сборка докер контейнера отсутствует, соответственно нереализован компоуз;
2. При написании следует учитывать, что код может часто меняться, поэтому следует подумать о его расширении и дальнейшей поддержке:
- при изменении количества городов код придется править
- при сборе дополнительных параметров погоды код придется править
- выбрана неоптимальная БД
3. Логирование выполнено принтами
Желаю Вам успехов.

**Comment by ss3nclam** [comment]
sd

**Comment by ss3nclam** [comment]
@SergSukh

Доброго времени суток. Внёс правки по фидбэку.

**Comment by ss3nclam** [comment]
Внёс правки по фидбэку.
